[package]
name = "blog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.4", features = ["derive"] }
env_logger = "0.10.0"
grass = "0.12.2"
log = "0.4.17"
markdown = "0.3.0"
serde = { version = "1.0.152", features = ["derive"] }
toml = "0.7.1"
